server.port: 8080

spring.application.name: gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://product-composite/products
          predicates:
            - Path=/products/**, /products

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

#no agafa be el link localhost i agafa el nom del portatil
#aixo ho arregla a la meitat, la resta de solucio
#esta a application.yml
spring.cloud.discovery.enabled: true
spring.cloud.gateway.discovery.locator.lower-case-service-id: true
spring.cloud.gateway.discovery.locator.enabled: true
eureka.instance.hostname: localhost

---
spring.config.activate.on-profile: docker