server.port: 7002

spring.application.name: recommendation

spring.cloud.stream.bindings.recommendationReceiverChannel.destination: recommendationChannel
spring.cloud.stream.bindings.recommendationReceiverChannel.group: recommendation


---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/product
    username: root
    password: root

server.port: 8080