version: '2.1'

services:
  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    build: gateway
    mem_limit: 350m
    ports:
      - "8080:8080"

  eureka:
    build: discovery
    mem_limit: 350m

  my-product-service:
    build: productService
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      docker-mysql:
        condition: service_healthy

  my-review-service:
    build: ReviewService
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      docker-mysql:
        condition: service_healthy

  my-recommendation-service:
    build: recommendations
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      docker-mysql:
        condition: service_healthy

  product-composite:
    build: product-composite
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  docker-mysql:
    image: mysql:5.7
    mem_limit: 350m
    #ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
        - my-datavolume:/var/lib/mysql
volumes:
        my-datavolume: