server.port: 8888
spring.profiles.active: native
spring.cloud.config.server.native.searchLocations: file:./config-repo

spring.security.user.name: "dev-usr"
spring.security.user.password: "dev-pwd"

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

health:
  config:
    enabled: false

logging.level.root: info

---
spring.config.activate.on-profile: docker

spring.cloud.config.server.native.searchLocations: file:/config-repo